/**
 * docx-reader.ts
 *
 * Extracts per-page plain text from a .docx file by reading the internal XML.
 *
 * A .docx file is a ZIP archive. The document body lives in word/document.xml.
 * Text is stored in <w:t> elements; explicit page breaks are marked with
 *   <w:br w:type="page"/>
 *
 * This approach works reliably for .docx files generated by our own
 * word-generator (which inserts explicit page breaks between pages). For
 * externally created Word files, only hard page breaks will be detected.
 */

import { readFile } from "node:fs/promises";
import JSZip from "jszip";

// ---------------------------------------------------------------------------
// XML entity decoding
// ---------------------------------------------------------------------------

function decodeXmlEntities(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'");
}

// ---------------------------------------------------------------------------
// Text extraction from an XML segment
// ---------------------------------------------------------------------------

/**
 * Extract plain text from a slice of word/document.xml.
 *
 * Strategy:
 *  1. Split the segment at paragraph boundaries (</w:p>).
 *  2. Within each paragraph, collect all <w:t> content.
 *  3. Join paragraphs with newlines; preserve tab characters from <w:tab/>.
 */
function extractTextFromSegment(xml: string): string {
  const paragraphs = xml.split(/<\/w:p>/i);
  const lines: string[] = [];

  for (const para of paragraphs) {
    let paraText = "";

    // Replace <w:tab/> with a literal tab
    const withTabs = para.replace(/<w:tab[^>]*\/?>/gi, "\t");

    // Extract all <w:t> text content
    const tPattern = /<w:t(?:\s[^>]*)?>([^<]*)<\/w:t>/gi;
    let m: RegExpExecArray | null;
    while ((m = tPattern.exec(withTabs)) !== null) {
      paraText += decodeXmlEntities(m[1] ?? "");
    }

    if (paraText) {
      lines.push(paraText);
    }
  }

  // Join paragraphs, collapse runs of 3+ newlines
  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trim();
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Extract per-page text from a .docx file.
 *
 * Pages are delimited by explicit page break markers:
 *   <w:br w:type="page"/>
 *
 * Returns an array where index 0 = page 1 text, index 1 = page 2 text, etc.
 * If no explicit page breaks are found, the entire document is returned as
 * a single-element array.
 */
export async function extractDocxPages(docxPath: string): Promise<string[]> {
  const buffer = await readFile(docxPath);
  const zip = await JSZip.loadAsync(buffer);

  const xmlFile = zip.file("word/document.xml");
  if (!xmlFile) {
    throw new Error(`word/document.xml not found inside "${docxPath}"`);
  }

  const xml = await xmlFile.async("string");

  // Split at explicit page break markers
  // These appear as: <w:br w:type="page"/> or <w:br w:type='page'/>
  const PAGE_BREAK_RE = /<w:br[^>]+w:type=["']page["'][^>]*\/?>/gi;
  const segments = xml.split(PAGE_BREAK_RE);

  return segments.map(seg => extractTextFromSegment(seg));
}
